### ISSUE TITLE
ffmpeg를 이용하여 비디오 섬네일 생성

### ISSUE THREAD

**Issue by huhani** [huhani/xe-simple-mp3-player#12]
ffmpeg가 사용이 가능한 상태이고, 비디오 파일이지만 description엔 poster항목이 없는 경우.
1. description생성이 최초일때
-> description 생성할 때 비디오 poster도 같이 생성.

2. description은 이미 생성되어 있으나 poster항목만 추가하면 될 때
-> description에서 poster만 추가한 뒤, 업데이트.

**Comment by huhani** [comment]
게시글 섬네일 적용 방식
1. img태그를 이용한 삽입
2. procFileSetCoverImage를 이용하여 게시글에 첨부된 이미지를 섬네일로 강제 등록.

1,2번을 운영자가 선택 할 수 있게.

**Comment by wookho** [comment]
@huhani 오늘 다운받아 적용해 봤는데 mp4 섬네일이 만들어지지 않네요.
이미 서버에 /usr/bin/ffmpeg 경로로 설치되어 다른 자료에서 사용하고 있습니다.

XE 최신버전입니다. 

일전에 알려주신
if(description) {
					if(description.filePath){
						description.filePath = ('https://img.domain.com/' + description.filePath).replace(/\/.\//, '/');
					}

이 부분만 추가해서 적용한 상태이구요. 다른 곳은 고친데는 없습니다.

**Comment by huhani** [comment]
@wookho 
애드온 설정에서
동영상 섬네일 사용 "사용", 게시글 섬네일 자동 적용 "사용" 으로 설정되었을때도 섬네일이 생성되지 않는가요?
혹시 해당 사이트 주소를 알려주시면 참고하는데 도움이 될 것 같습니다.

추가적으로 https://dev17.dnip.co.kr/index.php?mid=test 여기에도 일단 애드온을 적용하였는데, 테스트 부탁드립니다.

**Comment by huhani** [comment]
https://xetown.com/point_contents/1236834#comment_1288854
