### ISSUE TITLE
1.1.3 버전에서는 mp4가 변환되지 않네요

### ISSUE THREAD

**Issue by Mappy0824** [huhani/xe-simple-mp3-player#16]
mp4 링크만 남고 자동으로 변환되지 않습니다..

**Comment by huhani** [comment]
혹시 사이트 링크를 알려주실 수 있나요?

**Comment by Mappy0824** [comment]
http://langue824.dothome.co.kr/board/139

깃에서 받은 버전을 적용하고 그냥 mp4 링크 상태로 뒀을 경우 전 버전 처럼 자동으로 영상으로 보여주지않네여

원인이 무엇인지는 알게되었는데 일부러 빼신건가해서..
js 폴더에 비디오로 변환해주는 js가 빠졌고
php 부분에  js 로드하는부분도 전버전과 다르게 빠져있길래

이제 이 기능은 안쓰는건가요?

**Comment by Mappy0824** [comment]
아 그리고 이건 전버전에 있던 문제인데 신버전에도 해당되는진 모르겠지만..

AES Encryption, 미디어 URL 암호화 를 켜두고 활성화한상태에 mp3는 재생이 잘되지만
mp4 파일은 재생이 안되는 현상이 있습니다..

**Comment by huhani** [comment]
1.1.3 버전부터는 링크를 비디오,오디오를 변환하는 스크립트를 base.js로 통폐합 하였는데, 이 과정에서 일부 코드가 누락 된 듯 합니다.

https://github.com/huhani/xe-simple-mp3-player/commit/66e93dae0f56e5d057ad0cc555f01908e06b98dc
https://github.com/huhani/xe-simple-mp3-player/commit/af63a5982369d18ea53142b4d3804c75ba735aca

제보해주신 문제는 일단 해결하였습니다. 버그를 제보해주셔서 감사합니다.

P.S. 1.1.3버전에선 1.1.2버전에 비해 구조가 꽤 많이 변경이 되어 버그가 발생할 수 있는 점 양해바랍니다.
