### ISSUE TITLE
css 셀렉터

### ISSUE THREAD

**Issue by socialskyo** [huhani/xe-simple-mp3-player#2]
< div class="simple_mp3_player"></div >

값을 넣고
{$oDocument->getContent(false)}
< div class="simple_mp3_player"></div >

본문 하단에 집어 넣어도 상단에 계속 출력 됩니다.^^

**Comment by huhani** [comment]
현재로썬 css셀렉터가 혹시나 모를 보안 문제를 대비하여 무조건 본문 내에 있는 셀렉터로만 검색하도록 되어있습니다만..
css셀렉터가 전역에서 작동할 수 있도록 변경하겠습니다.

**Comment by huhani** [comment]
https://github.com/huhani/xe-simple-mp3-player/commit/1739bffcccddfd8cb77d4436c02b0464269cc591
