### ISSUE TITLE
3줄가사 출력방식이 다름

### ISSUE THREAD

**Issue by YJSoft** [huhani/xe-simple-mp3-player#5]
간혹 알송  싱크가사중 세줄가사를
```
시간: 가사1
가사2
가사3
```
이 아닌
```
0초: 가사1
0초: 가사2
0초-2초:가사3
```
처럼 구현한 것이 있는데 알송과 달리 APlayer는 가사3을 첫번째로 보여줍니다.

**Comment by huhani** [comment]
만약 lrc의 내용에 시간만 적혀있고 내용이 없거나 같은 시간대의 내용이 3줄을 넘어가버린다면
이후 같은 시간대의 내용은 필터링 되도록 구성이 되어있는걸로 알고 있습니다.

**Comment by huhani** [comment]
추가로 기존 APlayer에선 1줄가사만 지원해서 3줄이 뜰 수 있도록 수정한 APlayer 코드는 시간이 되면 별도로 올리겠습니다.
