### ISSUE TITLE
Magic Hash 취약점

### ISSUE THREAD

**Issue by kdps** [huhani/xe-simple-mp3-player#7]
발생할 확률이 아주 낮지만 혹시나 해서 이슈를 작성합니다.
* 별거 아닌 것 같으면 그냥 Close 해주세요.

현재 determineValidParameter 해시값이 SN으로 들어갑니다.
그러므로 substr(md5($text . SimpleEncrypt::getPassword()), 0, 12) <- 이 값이 무엇인지 유추가 가능합니다.

substr(md5($text . SimpleEncrypt::getPassword()), 0, 12)의 결과값이 
0e + 숫자 형식 (0e0021237373)
00e + 숫자 형식 (00e021237373)
000e + 숫자 형식 (000e1237373)...
으로 돼있을경우 SN 파라미터값을 0e1234로 해놓으면 determineValidParameter를 무조건 통과합니다.

그 다음은 https://github.com/huhani/xe-simple-mp3-player/issues/6의 결과를 실행할 수 있게 됩니다.

![1517](https://user-images.githubusercontent.com/10580498/62405011-63964f00-b5d4-11e9-8c6c-9032cba53d1b.png)

**Comment by huhani** [comment]
https://github.com/huhani/xe-simple-mp3-player/commit/9506b272b31c65a5ab812c175b131fa7f3abd1b7
